# We will use docker to set up out environment, so don't use any particular
# language in Travis itself
language: generic

# Enable docker
sudo: required
services:
    - docker

# Disable automatic submodule fetching (it's done recursively)
git:
    submodules: false

# Global environment variables
env:
    global:
        - DIST=xenial
        # Make sure beaver is in the PATH
        - PATH="$(git config -f .gitmodules submodule.beaver.path)/bin:$PATH"

# Do a shallow submodule fetch
before_install: git submodule update --init

# Don't build tags already converted to D2
if: NOT tag =~ \+d2$

# Create docker images and setup environment to build
install: beaver dlang install

# Basic config is inherited from the global scope
jobs:
    templates:
        - &test-matrix
          stage: Test
          script:
              - beaver dlang make
              # Build packages too, this should be done by beaver:
              # https://github.com/sociomantic-tsunami/beaver/issues/34
              - beaver dlang make pkg
    include:
        # Test matrix
        - <<: *test-matrix
          env: DMD=1.081.* F=production
        - <<: *test-matrix
          env: DMD=1.081.* F=devel
        - <<: *test-matrix
          env: DMD=2.070.*.s* F=production
        - <<: *test-matrix
          env: DMD=2.070.2.s* F=devel

        - stage: D2 Release
          # We need to include the exclusion of D2 tags because this "if"
          # replaces the global one
          if: tag IS present AND NOT tag =~ \+d2$
          # Some dummy env variables to make beaver happy
          env: DMD=2.070.2.s* F=devel
          script: beaver dlang d2-release
